version: '3.8'

name: immich-e2e

services:
  immich-server:
    container_name: immich-e2e-server
    command: ['./start.sh']
    image: immich-server:latest
    build:
      context: ../
      dockerfile: server/Dockerfile
    environment:
      - DB_HOSTNAME=database
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_DATABASE_NAME=immich
      - IMMICH_MACHINE_LEARNING_ENABLED=false
      - IMMICH_METRICS=true
    volumes:
      - upload:/usr/src/app/upload
      - ./test-assets:/test-assets
    depends_on:
      - redis
      - database
    ports:
      - 2283:3001

  redis:
    image: redis:6.2-alpine@sha256:d6c2911ac51b289db208767581a5d154544f2b2fe4914ea5056443f62dc6e900

  database:
    image: tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    command: -c fsync=off -c shared_preload_libraries=vectors.so
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: immich
    ports:
      - 5433:5432

volumes:
  model-cache:
  upload:
